apiVersion: v1
kind: Service
metadata:
  name: guestbook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: guestbook
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
