apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akuity-argocd-kargo-quickstart
spec:
  project: akuity-argocd-kargo-quickstart
  source:
    repoURL: https://github.com/dhpup/akuity-argocd-kargo-quickstart.git
    path: kargo
  destination:
    name: in-cluster
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
