apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akuity-argocd-kargo-quickstart
spec:
  project: akuity-argocd-kargo-quickstart
  source:
    repoURL: https://github.com/ernestourquijo/akuity-argocd-kargo-quickstart-shw.git
    path: kargo
  destination:
    name: kargo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
